apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
       # name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
  - name: name-of-service-port-nodeport
    protocol: TCP
    port: 80
    nodePort: 30007
   # targetPort: http-web-svc