apiVersion: v1
kind: Pod
metadata:
   name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine 
    command:
      - /bin/sh
      - "-c"
     # - "touch sample.txt"
      - "sleep 60m"
    args: [" echo 1 2 3 >> /opt/number.txt;"]
    volumeMounts:
      - mountPath: /opt
        name: data-volume 
  volumes: 
   - name: data-volume 
     hostPath: 
        path: /data
        type: Directory
