apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
spec: 
   replicas: 2
   selector: 
     matchLabels: ## It will manage the match label pod
       app: nginx 

   template: 
     metadata:
       name: nginx-pod1
       labels:
   # team: integrations
         app: nginx
     spec:
       containers:
        - name: nginx-container
          image: nginx:latest
          ports:
           - containerPort: 80

##Replicaset: Make sure that given no of replica always running all the time.

